# tasks file for tomcat
- name: create group {{tomcat_group}}
  group:
    name: "{{tomcat_group}}"
    state: present
  become: true
  become_method: sudo

- name: crate user {{tomcat_user}}
  user:
    name: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  become: true
  become_method: sudo

- name: create directory {{tomcat_home}}
  file:
    path: "{{tomcat_home}}"
    state: directory
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  become: true
  become_method: sudo

- name: Download tomcat
  get_url:
    url: "{{tomcat_link}}"
    dest: "{{tomcat_home}}/.."
  become: true
  become_method: sudo

- name: 'Extract tomcat'
  unarchive:
    src: "{{tomcat_home}}/../apache-tomcat-{{tomcat_version}}.tar.gz"
    dest: "{{tomcat_home}}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  become: true
  become_method: sudo

- name: 'copy tomcat.services'
  template:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
  become: true
  become_method: sudo
  notify:
    - restart tomcat

- name: "Start tomcat"
  systemd:
   state: started
   daemon_reload: yes
   name: tomcat
   enabled: yes
  become: true
  become_method: sudo



